language: ruby
rvm:
  - 2.5.3
sudo: false
script: bundle exec rake deploy
before_install: 
  - gem install bundler
env:
  global:
    secure: ma4gHZLn3erjqrSVMxqqD71SD4xfgMnJ/VdZ1je/poQMVjv8A3hInNkBKVh0Lz6vpF7zKGRMZ29zHg7uvYEslXAn06l1f8FI5XReltD5z2nEdnsFhKKvEXsOACtfDQXmw5qUuy9y2ra0BFjyzFPFtHD5zJhaEtSG/CbkEmHBlBhc53yNXvoEG8STDx9H4BGGC3Z3YgMrkn+qw6jhAXsVsRAi6ALeurfYwVm3xx7pst7P2BObx7Epe3+9b6fKw9OZupUJ507pMP2YHrZl3fLtv2Gn+L2Avl2q5rFImt4yHqTao2ivaEI2KzWUS0fgvI7RmZ33Sbf0/3b7CB4XMxqFH78g5LVxI6xyLT09JiMoxDdRtFmEM+MtYjIJGzPlPlx1DWJz2NVFYd+wjVJlqduiGKuXGMU967rh5j1+jQgAAp3WrHGGNRAgrskX6t43lXoHHZnnj8Ps3WwGJihsWUakCibLYV4S8kfxyPw9olApf2m10GV6x7rHCpof9Q9o2hubHW1AdxZESlbgvfMEXaS4EiiJbHVoTeMFCs88Z0SkY0dF3+J0exFNRgQLvVlUVDDF9Wrhmpqw3RTJoR/fzJFxKv/wsOZfkktnWthkqNdVSBlPFj/v6JJr7eyawjXIGT4GT46x+8GLDVys3egXfvMCJ+XdLABZdJRnwTIYJdqC8Yk=
