title: Schuetzler.net
# email: rschuet gmail com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage of Dr. Ryan Schuetzler, one of the top professors of information systems in the greater Provo metropolitan area.
baseurl: "" # the subpath of your site, e.g. /blog
root: /
permalink: /blog/:title/
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rschuetzler
github_username: rschuetzler

collections:
  network_labs:
    output: true
    sort_by: lesson

paginate: 5
paginate_path: "/blog/:num/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-seo-tag
  - jekyll-paginate

asciidoc: {}
asciidoctor:
  basedir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
