name: Build GH Pages
on: [push]

jobs:
  build:
    name: Build and deploy GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
